### ISSUE TITLE
[Drak Mode Functionality] I want to add dark mode functionality in this project.

### ISSUE THREAD

**Issue by Manishak798** [tamalCodes/Milan#1001]
### Description

Nowadays, websites do have a feature of dark mode that will provide ease to the visitor to switch between the modes accordingly and this will enhance the overall UI/UX experience.
I want to a dark theme toggler in the nav bar of the website by using JavaScript and CSS3. I am willing to work on this functionality please assign this to me under GSSOC23.

### Screenshots

![image](https://github.com/tamalCodes/Milan/assets/90680330/514a395c-efcd-42e9-bb71-97fdf398b93d)

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/tamalCodes/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)
- [X] I am a GSSoC23 contributor (blank for no).

**Comment by tamalCodes** [comment]
Hi there right now we are going through alot of UI changes. Specially if you have seen our beta changes, at https://beta.milanhub.org, so unfortunately we will be closing this. Thankyou so much for raising the issue.
