### ISSUE TITLE
[FEATURE] Lack of error handling when the category parameter in the URL is not valid

### ISSUE THREAD

**Issue by tamannaaaaa** [tamalCodes/Milan#1002]
### Description

One potential issue I noticed in the code is the lack of error handling when the category parameter in the URL is not valid. If the category parameter is not one of the predefined values ("art," "decors," or anything else), the component might not display the correct content or could break.

To address this issue, I can add a check to ensure that the category parameter is valid before rendering the component. If the category is not recognized, I can display an error message or redirect the user to a 404 page.

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/tamalCodes/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)
- [X] I am a GSSoC23 contributor (blank for no).

**Comment by tamalCodes** [comment]
Hi there i am closing this issue as of now, the whole shops page were taken down because of severe issues and lack of development. Will be started soon with a new UI.
