### ISSUE TITLE
[OTHER] Increase spacing in the banner for better mobile view

### ISSUE THREAD

**Issue by poorvijn** [tamalCodes/Milan#694]
### What would you like to share?

I noticed that on mobile, the banner text appears slightly too put together. I feel we could do with a bit more spacing between the heading 'Welcome to MILAN' and the paragraph that follows.

Here is how it looks for now:

![gssocfinal](https://github.com/IAmTamal/Milan/assets/87180220/3b162374-44e9-419b-90ea-537792da6962)

Could this issue be assigned to me under GSSoC? 

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by IAmTamal** [comment]
Sounds great, you can start working on it. Also, is this a part of the GSSOC'23 program ?

**Comment by poorvijn** [comment]
Yup, this is a part of GSSoC'23

**Comment by poorvijn** [comment]
hello, I couldn't figure out how to check if the spacing is right, so I guess it's okay. Thank you, I'll close this issue. I tried checking for responsiveness on mobile but the spacing looked fine.
