### ISSUE TITLE
[FEATURE] Add Location Based Search

### ISSUE THREAD

**Issue by suzy-g38** [tamalCodes/Milan#710]
### Description

Both in the Events and Clubs section if we add some filters, like for example location(for now), that will be easier for the user to find activities of their choice.

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by IAmTamal** [comment]
That's a great feature - i am assuming to make the filters work, we will be using `address` parameter of the clubs.
Assigning it to you, do make sure it's worked upon quickly 🚀🚀

**Comment by suzy-g38** [comment]
> That's a great feature - i am assuming to make the filters work, we will be using `address` parameter of the clubs. Assigning it to you, do make sure it's worked upon quickly 🚀🚀

Hey, I am really sorry I didn't check your reply sooner. Yes, I used the address for clubs and event location for events to sort the data but suddenly I had the idea of using geolocation. Share your thoughts on this. If you want it the way it is already(by using filter) then its okay, mostly everything is ready, I will push otherwise we can use geolocation.

**Comment by tamalCodes** [comment]
Hi @suzy-g38 , how do you plan on using the geo location ? 
I mean when someone is making an event/club, they are not adding anything related to `geolocation` - so I was wondering how would everything work.

Would really appreciate if you can elaborate this !

**Comment by suzy-g38** [comment]
> Hi @suzy-g38 , how do you plan on using the geo location ? I mean when someone is making an event/club, they are not adding anything related to `geolocation` - so I was wondering how would everything work.
> 
> Would really appreciate if you can elaborate this !

Actually, both have some merits and demerits, if you consider the current scenario, there is no common pattern in the location or address, some have a city mentioned in them, some have state and some have neither. If you see the popular websites then they all use search functions based on cities. Now if the future implementations will have a particular format then we can proceed without using geolocation. 
But if you are saying giving a format may give my user some restrictions, then I think geolocation can be a reasonable option. As the user is not giving any exact data, there is a package name react-geocode(if I didn't misspell it), which basically takes the name of a location and provides its corresponding lat and long value. Now if we get the user's current location using geolocation, then we can tally them and give all the events near them. Now the demerit is it can be costly.

Now it's your call, without the geolocation model is ready,  There are some predefined popular cities, the user will click on a city, and will get the desired result. I have used the "includes" method in clubs, as it is in the address format. For events, it is a normal value check. Tell me what suits you.

**Comment by tamalCodes** [comment]
Interesting, so how about working on a valid address too ? 
If someone is registering with the club, I just wanna make sure that they are entering a "valid" address. Can we use any libraries for that ? Because that way then we can use `geolocation` or anything to search the places. I want to pull it of as user-friendly as possible.

**Comment by suzy-g38** [comment]
> Interesting, so how about working on a valid address too ? If someone is registering with the club, I just wanna make sure that they are entering a "valid" address. Can we use any libraries for that ? Because that way then we can use `geolocation` or anything to search the places. I want to pull it of as user-friendly as possible.

@tamalCodes if you don't mind can we have meet regarding this? honestly writing everything is time-consuming and can leave many doubts on both sides. Just for your information, You can choose the time and day. Only I can't be available on Monday, otherwise, any day is good for me.
Let me know what you prefer.

And as for your answer, if you allow me we both can work on the address validation too, rather I would love to do that.

**Comment by tamalCodes** [comment]
Yaa no worries, how about today 8:30 pm ?

**Comment by suzy-g38** [comment]
> Yaa no worries, how about today 8:30 pm ?

Okay no, issue

**Comment by tamalCodes** [comment]
> > Yaa no worries, how about today 8:30 pm ?
> 
> Okay no, issue

cool, we will connect then. Join at [tamaldas.com/meet](https://www.tamaldas.com/meet), 8:30 PM
