### ISSUE TITLE
[FEATURE] Authentication by Google

### ISSUE THREAD

**Issue by Santosh7017** [tamalCodes/Milan#711]
### Description

Hii @IAmTamal 
I am willing to add authentication method by google account for users to Login/Register using Google OAuth.

Benefits :
1. This is one of the most authentic way to authenticate user
2. It is reliable and secure
3. Most of the users trust on google
4. It fast and responsive

Approach:
To add this feature, I propose the following steps:

To implement this feature we will use Passport which is authentication middleware for Node.js
We will setup passport google oauth2 strategy
We will generate a OAuth client id
then verify the user using Google Account
Save the user data into database
Additional Information:

As a proud participant of GSSOC3, armed with my extensive experience in similar projects, I possess the unwavering confidence to skillfully incorporate this feature .

Thank you for considering my involvement in resolving this issue. I am eager to collaborate with the team to ensure the successful implementation of the necessary improvements.

### Screenshots

![image](https://github.com/IAmTamal/Milan/assets/73546536/67d1d444-5cc6-4ef2-bfca-61924aaa134a)

<img width="960" alt="image" src="https://github.com/IAmTamal/Milan/assets/73546536/a8255b63-ca6c-422f-a950-52570a2b20ca">

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by IAmTamal** [comment]
Hi @ Santosh7017, this sounds really cool - however, I want to ask that since this is of such a vast size we can break this into 2 parts. Firstly you set up the backend needed, along with adding essential stuff to the `.env.example` file - so that I know what are the things that I need to add up next.

Then maybe we can develop the button which does the next steps thus a total authentication workflow.
So are you willing to start working on it now ?

**Comment by Santosh7017** [comment]
Certainly! I am fully prepared to commence work on the project immediately. I will begin by setting up the backend components, followed by the implementation of the frontend elements. This sequential approach will ensure a smooth and easily comprehensible workflow.

**Comment by Santosh7017** [comment]
> Hi @ Santosh7017, this sounds really cool - however, I want to ask that since this is of such a vast size we can break this into 2 parts. Firstly you set up the backend needed, along with adding essential stuff to the `.env.example` file - so that I know what are the things that I need to add up next.
> 
> Then maybe we can develop the button which does the next steps thus a total authentication workflow. So are you willing to start working on it now ?



Certainly! I am fully prepared to commence work on the project immediately. I will begin by setting up the backend components, followed by the implementation of the frontend elements. This sequential approach will ensure a smooth and easily comprehensible workflow.

**Comment by IAmTamal** [comment]
Sounds great, you can start working @Santosh7017 ⚡

**Please make sure that you have read our documentation on [Commiting guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#commits-) and [Pull request guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#pull-requests-), without proper format the PR might be closed.**

**Comment by Sa91001** [comment]
Hi there, it has been a while. I would love to know what changes you are making and/or are working on this.

**Comment by Santosh7017** [comment]
Hey I had sent you a message last Saturday on LinkedIn regarding progress and  I have been eagerly awaiting your response.

**Comment by tamalCodes** [comment]
> Hey I had sent you a message last Saturday on LinkedIn regarding progress and I have been eagerly awaiting your response.

Hi can you paste the same here ? it would be better.

**Comment by Santosh7017** [comment]
I am writing to you today to update you on my progress with implementing the Google authentication feature. I have made some good progress, but I am currently facing an issue with creating users that I tried to get user's address and pincode from google account but unable to get address and pincode, and also many users don't save their address in their google account, I wanted to seek your guidance on the necessity or mandatory requirement of storing the address during the user registration process. If it is deemed necessary, I am prepared to explore alternative methods to gather this information. Otherwise, the backend part of the feature is ready.

**Comment by tamalCodes** [comment]
So this is what can be done, we can put the `address` and `pincode` part to be optional by removing the `required: true,` or making it false. In that way, the user can simply signup. And can later choose their address and pin code. 

We will be also refactoring the address part so don't worry about that.

But we also need to make sure the user can log in via Google. There are 2 things that are returned in if the user would log in via email. I want to make sure they are logged in properly for the same.

![image](https://github.com/tamalCodes/Milan/assets/72851613/f2087646-e947-48b2-82eb-351104e07113)

**Comment by Santosh7017** [comment]
Ya sure I will take care of that

**Comment by tamalCodes** [comment]
Do make a PR once done ⚡ - we can review and work on it together then.

**Comment by Santosh7017** [comment]
Hey there, I am going to start working on frontend part so should I start working or open pull request of backend any suggestion?

**Comment by tamalCodes** [comment]
Well since this is a huge feature I would recommend doing slowly and step by step - if the backend is done, let's make a PR, and we can close this issue - then you can raise another issue for Frontend , where we will be integrating the FE with the already coded server-side codes.

Does that sounds good ?
