### ISSUE TITLE
Shopping cart icon not working in shop page [BUG] 

### ISSUE THREAD

**Issue by gaur15** [tamalCodes/Milan#717]
### Description

I tried opening the shopping cart or bag icon under shop section it didn't open 

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by guptaanshik1** [comment]
Can you please assign me this issue. I will look into this

**Comment by tamalCodes** [comment]
Hi there, I just noticed [here](https://github.com/tamalCodes/Milan/issues?q=is%3Aissue+cart+sort%3Acreated-asc) that the add-to-cart issue was already raised in #708 , so I would like to wait for them to work!
