### ISSUE TITLE
[FEATURE] Hover State On Navbar Links

### ISSUE THREAD

**Issue by Souravvmishra** [tamalCodes/Milan#734]
### Description

Links in the navbar or in general should have a hover state to add interactivity to the user & website. It is a small thing but adds a lot to the user experience.

Currently there is effect (underline effect) for the active links and nothing for the hover state links 

### 🥦 Browser

Brave

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by IAmTamal** [comment]
Sounds great, you can start working on it ⚡

**Please make sure that you have read our documentation on [Commiting guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#commits-) and [Pull request guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#pull-requests-), without proper format the PR might be closed.**

**Comment by Sa91001** [comment]
Hi there, it has been a while. I would love to know what changes you are making and/or are working on this.

**Comment by ujjawaltyagii** [comment]
Hey  @Sa91001 @tamalCodes  ! It seems that this issue is inactive from last two weeks if it is possible then I would like to work on this issue. So you can assign me this issue under gssoc I will try to wrap up this issue as soon as possible :)

**Comment by Souravvmishra** [comment]
I'm really sorry for the delay. There were some personal problems on acccount of which the delay was caused. I have made the proper PR. Please have a look at the same.

**Comment by tamalCodes** [comment]
> I'm really sorry for the delay. There were some personal problems on acccount of which the delay was caused. I have made the proper PR. Please have a look at the same.

Cool.
