### ISSUE TITLE
Creating api for add to cart 

### ISSUE THREAD

**Issue by Ja3mamtora** [tamalCodes/Milan#757]
### Description

Need to improve model and add api for add to cart 

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by IAmTamal** [comment]
That's a great issue but i'd like to wait until #700 is completed then we can go ahead and make it.
Thanks for the thought, I'll lock this for now.

**Comment by tamalCodes** [comment]
I just noticed [here](https://github.com/tamalCodes/Milan/issues?q=is%3Aissue+cart+sort%3Acreated-asc) that the add-to-cart issue was already raised in #708 , so i would like to wait them to work !
