### ISSUE TITLE
[BUG] Navbar Not Closing on Clicking Outside in Small and Medium Screens

### ISSUE THREAD

**Issue by Kalyan-velu** [tamalCodes/Milan#759]
### Description

On small and medium screen sizes, the website's navbar has a hamburger button that opens and closes the navbar upon clicking. However, there is a bug where the navbar does not automatically close when clicking outside of the navbar component.

### Reproduction Steps
Open the website with a smaller screen size using the browser's devtools.
Click on the navbar menu button to open the navbar.
Attempt to close the navbar by clicking outside of the navbar component.

### Expected Behavior
The expected behavior is that the navbar should close when clicking outside of the navbar component in order to provide a better user experience.

### Browser 🥦

Microsoft Edge

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by IAmTamal** [comment]
Great spot, you can start working on it ⚡

**Please make sure that you have read our documentation on [Commiting guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#commits-) and [Pull request guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#pull-requests-), without proper format the PR might be closed.**
