### ISSUE TITLE
[FEATURE] Minimal animations to the "here" in footer

### ISSUE THREAD

**Issue by qwertyroop** [tamalCodes/Milan#761]
### Description

Currently, the link "here" on our website is colored orange to make it stand out. However, we believe that adding an underline animation to the link would further enhance its visibility and improve the overall user experience.

The main goal of this issue is to implement an underline animation for the link "here" on our website. By doing so, we aim to draw more attention to the link and provide visual feedback to users when they hover over it.

Once implemented, this enhancement will provide a visually appealing and interactive experience for users, making it easier for them to identify and navigate through important links on our website.

### Screenshots

![Screenshot 2023-05-26 122955](https://github.com/IAmTamal/Milan/assets/45703076/18a68493-f922-485f-89b1-02ec5b893326)

### 🥦 Browser

Brave

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by IAmTamal** [comment]
That would a be nice little animation, you can start working on it ⚡

**Please make sure that you have read our documentation on [Commiting guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#commits-) and [Pull request guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#pull-requests-), without proper format the PR might be closed.**

**Comment by qwertyroop** [comment]
Sure thank-you, much Appreciated ♥️
