### ISSUE TITLE
[FEATURE] Thinking to create a rating component in react  

### ISSUE THREAD

**Issue by Nitish-hack** [tamalCodes/Milan#765]
### Description

currently product card is showing rating statically 
![image](https://github.com/IAmTamal/Milan/assets/106099275/913aecc7-fc5e-4099-9e00-5d484c822b02)

a rating component is needed in which if we pass rating as props it displays the rating ...this will help in dynamic display of rating 

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by Nitish-hack** [comment]
please assign this issue to me under GSSOC'23

**Comment by tamalCodes** [comment]
Hi, @Nitish-hack I appreciate your motivation to work, but please we need to take things slowly and step by step.

You currently have #766 and #701 assigned to you, please make sure those are merged and then we can proceed with these. I will be temporarily putting these on hold. Thanks.
