### ISSUE TITLE
[FEATURE] Thinking to create a Format Price component in react

### ISSUE THREAD

**Issue by Nitish-hack** [tamalCodes/Milan#766]
### Description

currently price is being display statically ie. 100  , ......... what if price has  more digits lets say 18000 ..........Format Price component is needed that will format the price in indian system ........i.e. it will automatically add  rupee symbol ....add commas 

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by Nitish-hack** [comment]
please assign this issue to me under gssoc'23

**Comment by Nitish-hack** [comment]
any update or any other issue i can work on

**Comment by tamalCodes** [comment]
Hi @Nitish-hack , this looks like a great issue, make sure it works for all the numbers. The styles musn't change.

**Please make sure that you have read our documentation on [Commiting guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#commits-) and [Pull request guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#pull-requests-), without proper format the PR might be closed.**
