### ISSUE TITLE
[BUG] Improve Contact Us page responsiveness

### ISSUE THREAD

**Issue by rahulaarora** [tamalCodes/Milan#771]
### Description

The contact form in the contact us page at 770px to 990px width on desktop view is not responsive. The lower contact form fields and submit button get hidden behind the footer and the user is not able to submit the form.

### Screenshots

<img width="948" alt="Screenshot 2023-05-27 at 11 56 47 PM" src="https://github.com/IAmTamal/Milan/assets/24794534/bcf4354a-eb10-487f-aded-cf4a5d2bcc39">

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
A great issue, The contact us page really needs some love ⚡
You can make a PR and we can then work on it together.

**Please make sure that you have read our documentation on [Commiting guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#commits-) and [Pull request guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#pull-requests-), without proper format the PR might be closed.**

**Comment by Sa91001** [comment]
Hi there, it has been a while. I would love to know what changes you are making and/or are working on this.

**Comment by rahulaarora** [comment]
Hi @Sa91001,
sorry for the delay, due to my college
I just opened the PR, have a look!
