### ISSUE TITLE
[FEATURE] Grammatical and spelling errors in the website

### ISSUE THREAD

**Issue by HimanshuNarware** [tamalCodes/Milan#772]
### Description

Website content lots of grammatical and spelling errors, I want to resolve them, Kindly assign me 

### Screenshots

![59](https://github.com/IAmTamal/Milan/assets/83147410/35cbfd53-52e5-4298-8748-ececc14d56f5)
![6-](https://github.com/IAmTamal/Milan/assets/83147410/95969463-a8db-4fbd-8d11-0fc3456f9cc8)

### 🥦 Browser

Brave

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
Cool, you can start working on it and make a PR ⚡

**Please make sure that you have read our documentation on [Commiting guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#commits-) and [Pull request guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#pull-requests-), without proper format the PR might be closed.**

**Comment by Sa91001** [comment]
Hi there, it has been a while. I would love to know what changes you are making and/or are working on this.
