### ISSUE TITLE
Clicking on the footer icon doesn't navigate to home

### ISSUE THREAD

**Issue by Srija-Burugula** [tamalCodes/Milan#774]
### Description

In the current version of the website, clicking on the footer icon doesn't navigate to home. Adding this would enhance the  UI. I would like to solve this issue under GSSoC'23. Please assign this issue to me.

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
Which icon are we talking about ?

**Comment by Srija-Burugula** [comment]
In the footer, there is no back to home button. I would like to add that option. please assign this issue to me under GSSoC'23

**Comment by tamalCodes** [comment]
Well we would like to use another approach, instead of the footer having a link to home, how about making the navbar sticky? That way the user can whenever want, switch pages without having to worry. Does this sound good ?

**Comment by Srija-Burugula** [comment]
sure sir, I would like to work on this. Please assign this issue to me.

**Comment by tamalCodes** [comment]
> sure sir, I would like to work on this. Please assign this issue to me.

Cool, you may start working on this. Assigning this to you ⚡

**Please make sure that you have read our documentation on [Commiting guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#commits-) and [Pull request guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#pull-requests-), without proper format the PR might be closed.**

**Comment by Srija-Burugula** [comment]
Thank you sir.

**Comment by tamalCodes** [comment]
> Thank you sir.

Just call me Tamal, i'm still in College.

**Comment by Srija-Burugula** [comment]
Ok

**Comment by sshiwangi** [comment]
Hey @tamalCodes, If it's not done yet, can I work on this issue under GSSOC'23?

**Comment by Srija-Burugula** [comment]
@tamalCodes I'm working on it. I'll complete it ASAP.
