### ISSUE TITLE
[BUG] Different size buttons for mobile

### ISSUE THREAD

**Issue by elhussienalmasri** [tamalCodes/Milan#778]
### What would you like to share?

in mobile devices "contribute to Milan button" bigger than "Sign up button",
I think it ,s good for styling to make them equal .

![Milan](https://github.com/IAmTamal/Milan/assets/90080237/59e60987-d8aa-4f54-b622-0aef75b85fdc)

 

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by elhussienalmasri** [comment]
please assign this issue for me

**Comment by tamalCodes** [comment]
Hi @elhussienalmasri , let us wait for #775  to be merged.

**Comment by tamalCodes** [comment]
Hi @elhussienalmasri , sorry for the delay - it seems that #775 is inactive. Therefore I have closed their PR.
You can start working on this, and if you want you can also work on #775. I am unlocking the thread and assigning this to you. 
### Good PR makes a Good Developer !

We at Milan work hard to maintain the structure, and use conventional Pull request titles and commits.
**Please make sure that you have read our documentation on [Commiting guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#commits-) and [Pull request guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#pull-requests-).**

Without a proper template for the PR, not following the guidelines and spam might get the pull request closed, or banned.

**Comment by elhussienalmasri** [comment]
Hi @tamalCodes , I already sent PR , and yes I can work on the other issue , but after this issue get merged , and 
make sure no one work on the other issue cause the other developer already sent PR.
