### ISSUE TITLE
[FEATURE] Add GoToTop Button

### ISSUE THREAD

**Issue by abhi03ruchi** [tamalCodes/Milan#787]
### Description

I would like to add a back to top button in the website to improve user experience and engagement.

Plz assign me this task under gssoc'23.

### Screenshots

Sample :- > 
https://github.com/tamalCodes/Milan/assets/105661636/45a2d4d2-ca15-4d14-82b1-1ea4e203b9d0

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
Hi, it is been worked in #696 , please donot raise duplicates.
