### ISSUE TITLE
[DOCS] Fix link to github profile in issue forms

### ISSUE THREAD

**Issue by Anmol-Baranwal** [tamalCodes/Milan#791]
### Description

- As you can see in the screenshot, the GitHub profile link `here` is not working correctly.
- I will update all the issue forms to fix the link.
- This will be a quick issue, and I will make a PR as soon as you assign me the issue.

> I would like to contribute to this issue under GSSoC'23.

### Screenshots

![image](https://github.com/tamalCodes/Milan/assets/74038190/2b203dcb-f78b-48d4-ab5c-0bf2e0f8258a)

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
Cool, do make a PR once done ⚡

**Please make sure that you have read our documentation on [Commiting guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#commits-) and [Pull request guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#pull-requests-), without proper format the PR might be closed.**
