### ISSUE TITLE
[BUG] Fix responsiveness issue with clubs page heading

### ISSUE THREAD

**Issue by Chirayu31** [tamalCodes/Milan#793]
### Description

The current implementation of the clubs page heading in the project is not fully responsive, causing it to appear distorted and unattractive on certain screen sizes. This issue hampers the overall user experience and aesthetic appeal of the page. 

**Expected Behavior:**
- The clubs page heading should adjust its size and layout dynamically based on the screen size.
- The heading should look visually appealing and maintain its legibility across various devices and resolutions.

**Proposed Solution:**
To resolve this issue, I suggest the following steps:

- Identify the CSS code responsible for styling the clubs page heading.
- Add appropriate CSS rules and media queries to make the heading responsive.
- Test the changes thoroughly across various screen sizes and devices to ensure consistent and visually pleasing rendering.
- Make any necessary adjustments to ensure the heading remains readable and visually appealing in all scenarios.

### Screenshots

![Screenshot (22)](https://github.com/tamalCodes/Milan/assets/29854558/63c068c6-17be-4566-8521-bae4fc29b53e)
![Screenshot (23)](https://github.com/tamalCodes/Milan/assets/29854558/de8231c2-6a0b-4a85-b358-5932d2a53603)

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
That sounds good, but we have purposely used the `word-break: break-all` property so that huge words like `communities!` do not messes up the responsiveness when we are in smaller devices, what changes do you suggest ?

**Comment by Chirayu31** [comment]
Introducing a media query to target devices where the heading breaks and decreasing the font size can be a simple solution to maintain responsiveness across all devices.

**Comment by tamalCodes** [comment]
Well i think we can give this  a try ⚡

**Please make sure that you have read our documentation on [Commiting guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#commits-) and [Pull request guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#pull-requests-), without proper format the PR might be closed.**
