### ISSUE TITLE
[BUG] Adding Validation to pincode in Register as a User page

### ISSUE THREAD

**Issue by Sar-thak-3** [tamalCodes/Milan#796]
### Description

Validation of pincode length is already set in Register as NGO page, the same needs to be done in Register as a User page.

### Screenshots

![image](https://github.com/tamalCodes/Milan/assets/100359818/62646a6e-2fa4-40dc-b51b-41d29d1335b0)

### Browser 🥦

Microsoft Edge

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
Seems that we have missed it. You can start working on it - assigning it to you ⚡

**Please make sure that you have read our documentation on [Commiting guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#commits-) and [Pull request guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#pull-requests-), without proper format the PR might be closed.**
