### ISSUE TITLE
[FEATURE] API to fetch single product from the database

### ISSUE THREAD

**Issue by Nitish-hack** [tamalCodes/Milan#804]
### Description

To design a product description page , an API to fetch single product data from the database is needed .

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by Nitish-hack** [comment]
please assign this issue to me under gssoc'23

**Comment by tamalCodes** [comment]
Cool, you can start working on this ⚡

**Please make sure that you have read our documentation on [Commiting guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#commits-) and [Pull request guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#pull-requests-), without proper format the PR might be closed.**
