### ISSUE TITLE
Add Proper MVC (Model View Controller )Folder Structure 

### ISSUE THREAD

**Issue by JainPriya1234** [tamalCodes/Milan#807]
### Description

-I want to make a proper MVC folder structure that is followed in node.js.
-As it will help in debugging and modification quickly.
-And help others to contribute easily.
-As they can add features to the project easily because of the proper MVC(Model View Controller) folder structure.
please assign me this issue under gssoc23

### Screenshots

![image](https://github.com/tamalCodes/Milan/assets/91417671/5ada5535-c6b2-4db8-b21d-70adacff4070)

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by JainPriya1234** [comment]
@iakgoog @RXBlade @vancassa @kristiingco  please assign me this issue

**Comment by JainPriya1234** [comment]
@tamalCodes please review this issue

**Comment by tamalCodes** [comment]
Hi there, please stop tagging Random accounts in the comments, if such a thing is found again you will be banned.
![image](https://github.com/tamalCodes/Milan/assets/72851613/f58f0ebc-9b47-4d83-92bd-68a8bea9afae)

And about the structure what you are suggesting is real good - though I really don't want these changes right now - as we have ALOT of pending works that are currently going on and working on something major will end up breaking all those. We can do these later on.

**Comment by JainPriya1234** [comment]
Sorry @tamalCodes , i was unaware about the concerned person so I thought those were the mentors... please assign later this issue to me
