### ISSUE TITLE
[FEATURE] Recreate form for Events

### ISSUE THREAD

**Issue by suzy-g38** [tamalCodes/Milan#811]
### Description

I want to recreate the events form, as currently there is no such format in the create-events form. I want to add proper naming and autocomplete address search options which will be easier for the user to fill up the form.

I would like to work on it under GSSOC'23

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
Great issue, assigning it to you ⚡

We do have [EventCreate.jsx](https://github.com/tamalCodes/Milan/blob/main/src/pages/clubs/EventCreate.jsx), and also a potential schema for the same at [/server/models/EventSchema.js](https://github.com/tamalCodes/Milan/blob/main/server/models/EventsSchema.js) - maybe you can take the help of these to work around.  We will change some folder structure soon too, hope there's no conflicts.
