### ISSUE TITLE
[FEATURE] Add a Preloader in the website

### ISSUE THREAD

**Issue by vk20july** [tamalCodes/Milan#822]
### Description

Something like this
![d3f472b06590a25cb4372ff289d81711_w200](https://github.com/tamalCodes/Milan/assets/71543332/ed685685-6162-4823-b85d-77dd48b1d09f)

### 🥦 Browser

Opera

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
Hi there we already have a preloader on our website, which is fine. We will be closing this.
![image](https://github.com/tamalCodes/Milan/assets/72851613/c6b1ca1c-3166-411c-9fd7-851d1c19ddb1)
