### ISSUE TITLE
[DOCS] fix typo in CONTRIBUTING.md

### ISSUE THREAD

**Issue by rahulaarora** [tamalCodes/Milan#824]
### Description

Fix typographical and grammatical errors in `CONTRIBUTING.md`
 

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
Go ahead @rahulaarora , make sure there are duplicate spaces when you are committing. 

**Please make sure that you have read our documentation on [Commiting guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#commits-) and [Pull request guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#pull-requests-), without proper format the PR might be closed.**

**Comment by rahulaarora** [comment]
> Go ahead @rahulaarora , make sure there are duplicate spaces when you are committing.

like the same spaces in between the words of the file?
