### ISSUE TITLE
[FEATURE]  Want to add animation and hover effect on the Home page images

### ISSUE THREAD

**Issue by HimanshuNarware** [tamalCodes/Milan#829]
### Description

I want to add animation and hover effect on the Home page images, also the shop section product does not  have any hover effect , I want to  work on this issue, kindly assign me this issue.

### Screenshots

![177](https://github.com/tamalCodes/Milan/assets/83147410/c2d3a511-50b5-4765-b48a-6c512a4e8561)
![176](https://github.com/tamalCodes/Milan/assets/83147410/e6011962-6f23-4186-afee-ab6b266570c8)
![178](https://github.com/tamalCodes/Milan/assets/83147410/1d59836c-6edf-48d7-87ef-b208567b4f34)

### 🥦 Browser

Brave

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
Hi there, what type of animations are we talking about ? 
Would be better if you could explain in detail about the changes.

**Comment by HimanshuNarware** [comment]
> Hi there, what type of animations are we talking about ? Would be better if you could explain in detail about the changes.

 animation like gssoc website has in their home page image have
ok i add video 
https://github.com/tamalCodes/Milan/assets/83147410/0c0776c6-2aaf-4ae6-898c-70b70a44b0a0

**Comment by tamalCodes** [comment]
Hi @HimanshuNarware , thanks for clarifying - but i don't think we need animations like that - we like to keep things light and simple as it is.

Thankyou so much for giving this a thought.

**Comment by HimanshuNarware** [comment]
> Hi @HimanshuNarware , thanks for clarifying - but i don't think we need animations like that - we like to keep things light and simple as it is.
> 
> Thankyou so much for giving this a thought.

and what about the hover effect on the Trending production section product img hover effect
