### ISSUE TITLE
[FEATURE] Sign in/Signup form is missing a placeholder

### ISSUE THREAD

**Issue by HimanshuNarware** [tamalCodes/Milan#842]
### Description

The placeholder is missing on the Sign in/Signup page Which effecting the readability of the website, I want to work on this issue.

### Screenshots

##Screenshot
![213](https://github.com/tamalCodes/Milan/assets/83147410/2970b311-1fe3-423a-a450-b987bde2db53)

![211](https://github.com/tamalCodes/Milan/assets/83147410/922d0310-2773-4926-bc61-fb29d7cb41b3)
![212](https://github.com/tamalCodes/Milan/assets/83147410/ed116342-a24e-43b2-81e8-69f3c830f736)
![210](https://github.com/tamalCodes/Milan/assets/83147410/bba18085-5086-4e42-8b9a-f9ed131434db)

### 🥦 Browser

Brave

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
It is not missing. The placeholders are there for mobiles. For the desktop it is hidden as we are showing labels thus makes no sense to show the placeholders again. I hope this clears the misunderstanding, I will close the issue then !

![image](https://github.com/tamalCodes/Milan/assets/72851613/64effc0e-2351-48f9-88fd-72f5b7f6d719)
