### ISSUE TITLE
[BUG] Broken link under EXPLORE! field

### ISSUE THREAD

**Issue by SubhamB2003** [tamalCodes/Milan#843]
### Description

Hey, In the footer section under the "EXPLORE" field, the Shop and Event links are broken.

![image](https://github.com/tamalCodes/Milan/assets/94003231/cbf82fb3-a3cc-477e-815b-f1f73162d38b)

Please assign it to me under GSSOC'23.

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
Hi @SubhamB2003 , sorry for the delay - you can start working on it. Also there's another glitch I noticed. As soon as I signed in, we should technically move from `JOIN US` to `Explore Us` but for that to happen we need to refresh the whole page again. Please fix that behavior too.

![image](https://github.com/tamalCodes/Milan/assets/72851613/e3327d5d-ef63-4375-8cb2-64def5a318be)

**Comment by SubhamB2003** [comment]
@tamalCodes Hey, On the profile page there is no show password option so can I add this ? and you can increase the level here

**Comment by tamalCodes** [comment]
Hi @ SubhamB2003, the issue is you are not providing a proper commit message. We maintain our commit and PR title's standard by following best and conventional practices. Read more in our [contributing guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md#commits-).

Example can be: 

`fix: write whatever you fixed` ,  `docs: added documentation for joi validation` and so on. Everything must be in lowercase.

**Comment by SubhamB2003** [comment]
> Hi @ SubhamB2003, the issue is you are not providing a proper commit message. We maintain our commit and PR title's standard by following best and conventional practices. Read more in our [contributing guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md#commits-).
> 
> Example can be:
> 
> `fix: write whatever you fixed` , `docs: added documentation for joi validation` and so on. Everything must be in lowercase.

@tamalCodes Now is ok. Thanks for helping me
I created the pr can you please check
