### ISSUE TITLE
[FEATURE] A scroll to top button on all the  pages

### ISSUE THREAD

**Issue by karthiknadar1204** [tamalCodes/Milan#847]
### Description

Here I speak of a small component which could be rendered on all the pages, now when the user has scrolled down, instead of manually scrolling down, we could add a feature that causes a small scroll-up button to appear on the bottom right corner of the page when the navbar is out of view so now if the user wants to go back to the top of the page, instead of scrolling up manually, we the user can just click on this button and reach back up smoothly.

Refer to the following video for a better understanding of the feature I speak of, I implemented this in another r project

https://github.com/tamalCodes/Milan/assets/95973644/106cf25d-09e9-4bad-9b97-cebd22297dcc

### Screenshots

https://github.com/tamalCodes/Milan/assets/95973644/f8395dd8-bfa7-4adb-8d1b-763e4f02dcec

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by karthiknadar1204** [comment]
I would like to work on this issue under gssoc'23

**Comment by tamalCodes** [comment]
This has been assigned to #833 , please do wait - if they are not working on it by the next 5 days - I will revert back to you.
