### ISSUE TITLE
[FEATURE] Clubs and Event section have the same image in every box

### ISSUE THREAD

**Issue by HimanshuNarware** [tamalCodes/Milan#851]
### Description

#Description
The clubs and Event section content box  had a same image in every box, I want to add  images to the box according to the title of the event and club

Also the height of box need improvement and need hover effect
##Screenshot

### Screenshots

![221](https://github.com/tamalCodes/Milan/assets/83147410/f69b3875-f4b0-4ae1-894e-c3f33f905517)
![222](https://github.com/tamalCodes/Milan/assets/83147410/bd1fbc15-dac5-4e61-9f33-a2359381ded8)
![223](https://github.com/tamalCodes/Milan/assets/83147410/4aca0e28-cd33-4a10-b608-210726b01c89)

### 🥦 Browser

Brave

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
Hi @HimanshuNarware , this sounds fun  - but how are you planning to do so ?

**Comment by HimanshuNarware** [comment]
> Hi @HimanshuNarware , this sounds fun - but how are you planning to do so ?

I am thinking of adding images relative to the title of the box, like for health care events/clubs we can add which is related to health care. I think that images improve the readability of the website. What you think

**Comment by HimanshuNarware** [comment]
> I see here's what we are planning to do.
> 
> * Make the Backend ready to handle images so that we can users can put up their own images as per their event/club.
> * Then implement the frontend so that whenever someone registers their own NGO/Club the images can be added by the user as per their need.
> 
> The reason is currently we have a static set of images and we cannot add images based on the events, so it is best if the users do it. What do you think ?

Nice

**Comment by tamalCodes** [comment]
### Let's catch up !
Hi there, it has been a while since we last had a conversation so I wanted to know if you are still working on this. Please drop a reply shortly so that we know you are active, feel free to convey any problem you face in the comments, or mail me at tamalcodes@gmail.com.

**Comment by HimanshuNarware** [comment]
> ### Let's catch up !
> Hi there, it has been a while since we last had a conversation so I wanted to know if you are still working on this. Please drop a reply shortly so that we know you are active, feel free to convey any problem you face in the comments, or mail me at [tamalcodes@gmail.com](mailto:tamalcodes@gmail.com).

Nope! I am not well in backend

**Comment by tamalCodes** [comment]
Cool, well then it's better to close this issue for now - and once the API and schemas are all ready we can then start with it.
