### ISSUE TITLE
[BUG] Remove console logs from the website

### ISSUE THREAD

**Issue by Avinash905** [tamalCodes/Milan#854]
### Description

There are console.logs present in the project which is displaying sensitive information like passwords on the browser console. 
It is necessary to remove the console logs form the website to keep the data safe.

### Screenshots

![Screenshot (494)](https://github.com/tamalCodes/Milan/assets/56786344/e102d739-673d-48c2-99ec-0190b72cbadb)

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by Avinash905** [comment]
Please assign me this issue so that I can work on this issue under **GSSOC'23**.

**Comment by tamalCodes** [comment]
Hi , currently you have  #855 and #856  assigned, please complete those and then we can start to work on this.

**Comment by tamalCodes** [comment]
You can start working on this.

### Remember, Good PR makes a Good Developer !

We at Milan work hard to maintain the structure, and use conventional Pull request titles and commits.
**Please make sure that you have read our documentation on [Commiting guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#commits-) and [Pull request guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#pull-requests-).**

Without a proper template for the PR, not following the guidelines and spam might get the pull request closed, or banned.
