### ISSUE TITLE
Addition of Fixed Navbar Feature for Easy Navigation

### ISSUE THREAD

**Issue by arin-paliwal** [tamalCodes/Milan#860]
## Description
Currently, while scrolling down the screen, the navbar moves up with the page, making it difficult for users to navigate through the website. This behavior hinders the ease of access to important navigation elements, such as menu items or search functionality. To improve user experience and streamline navigation, we propose adding a fixed navbar feature.

## Proposed Solution
The proposed solution is to make the navbar fixed, ensuring that it remains visible and accessible to users at all times, even when scrolling down the page. This will allow users to quickly access the navigation menu and other essential features without having to scroll back to the top of the page.

## Benefits
- Enhanced user experience: Users can easily navigate through the website without losing access to the navbar.
- Improved efficiency: With a fixed navbar, users can perform actions such as accessing different pages, search, or menu options more quickly.
- Consistency: Keeping the navbar fixed will provide a consistent user interface, as it will always be present regardless of the user's position on the page.

## Implementation Suggestions
There are several ways to implement a fixed navbar feature, depending on the specific requirements of the project. Some possible approaches include:
- Using CSS positioning: Apply the `position: fixed;` property to the navbar element, along with appropriate CSS rules for styling and positioning.
- Utilizing JavaScript: Implement a JavaScript function that listens to the scroll event and updates the navbar's position accordingly.

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
Hi there, this is already been worked upon in #774 where the contributor has to [agreed](https://github.com/tamalCodes/Milan/issues/774#issuecomment-1584912072) to work on making the navbar not scroll away.  So for now I will be closing this issue - as it appears the same. 

Thanks.
