### ISSUE TITLE
[FEATURE] Text Selection Style to Match Website Theme

### ISSUE THREAD

**Issue by arin-paliwal** [tamalCodes/Milan#861]
## Description
Currently, when selecting text on the website, the default text selection background is blue with white text. However, this default style does not align with the overall theme of the website, which has a black color scheme. To enhance the visual consistency and improve the user experience, we propose revamping the text selection style to match the website's theme.

## Proposed Solution
The proposed solution is to update the text selection background and text color to align with the website's orange and black color scheme. This change will ensure that the text selection appears seamlessly integrated into the overall design, providing a more cohesive and visually appealing experience for users.

## Benefits
- Visual consistency: The revamped text selection style will match the website's theme, creating a more cohesive and aesthetically pleasing experience.
- Improved readability: By using appropriate colors for the text selection background and text, readability will be enhanced, making it easier for users to distinguish selected text from the surrounding content.
- Enhanced user experience: The updated text selection style will contribute to a more polished and professional feel, enhancing the overall user experience on the website.

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
Wow, this issue sounds good to me, please for the next time don't remove words like `[FEATURE]` from the start of the issue title.  Assigning this to you - make a PR once done ⚡

### Remember, Good PR makes a Good Developer !

We at Milan work hard to maintain the structure, and use conventional Pull request titles and commits.
**Please make sure that you have read our documentation on [Commiting guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#commits-) and [Pull request guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#pull-requests-).**

Without a proper template for the PR, not following the guidelines and spam might get the pull request closed, or banned.
