### ISSUE TITLE
[FEATURE] Sitemap Addition for Website {GSSoc'23}

### ISSUE THREAD

**Issue by NikhilRaikwar** [tamalCodes/Milan#867]
### Description

The current website does not have a sitemap, making it difficult for search engines and users to navigate and discover all the pages and content on the site. This can result in lower search engine rankings, decreased visibility, and a poor user experience.
I would like to request the addition of a sitemap to the website. A sitemap is a file that lists all the URLs and metadata of a website's pages. It helps search engines crawl and index the site more effectively, improving its visibility in search results. Additionally, a sitemap provides a structured overview of the website's content, allowing users to easily find and navigate to specific pages.

### Screenshots

![Screenshot (103)](https://github.com/tamalCodes/Milan/assets/70462831/3f5c0c67-7bfe-4429-a0d8-a8527dbc69d3)
Here screenshot shows that the website doesn't contain a sitemap.

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
Great issue, you can start working on this.
### Remember, Good PR makes a Good Developer !

We at Milan work hard to maintain the structure, and use conventional Pull request titles and commits.
**Please make sure that you have read our documentation on [Commiting guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#commits-) and [Pull request guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#pull-requests-).**

Without a proper template for the PR, not following the guidelines and spam might get the pull request closed, or banned.
