### ISSUE TITLE
[FEATURE] Change price of items under Shop tab

### ISSUE THREAD

**Issue by swapn652** [tamalCodes/Milan#868]
### Description

Under **Shop** tab, the cost of all items is same, i.e., 1000. It would look better if it was different for each item.

### Screenshots

 <img width="1186" alt="Screenshot 2023-06-19 at 7 48 46 PM" src="https://github.com/tamalCodes/Milan/assets/70851202/edb182e1-8025-4648-aa76-5af3dc22571e">

### 🥦 Browser

Brave

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
Those all are demo data for now - it will all be changed soon. Thanks for bringing this to our notice.
