### ISSUE TITLE
Charity Impact Map

### ISSUE THREAD

**Issue by Suchitra-Sahoo** [tamalCodes/Milan#881]
### Description

Milan can create an interactive "Charity Impact Map" that visually displays the geographical reach and impact of different charities, NGOs, and projects. This map can provide users with a comprehensive overview of the charitable activities happening around the world and allow them to explore and support causes that resonate with them. 

Kindly allow me to work on this issue under gssoc'23

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
Hi @Suchitra-Sahoo , i really don't understand the issue, please can you explain me in details ?

**Comment by tamalCodes** [comment]
### Notice 🚩

Hi there, unfortunately, I will have to close this Issue/PR, as this issue/PR has been inactive for quite a while and there's no work going on for the same.

There might be more Issues/PR which are waiting for this to be completed - so it is better to pace things up. I generally spend/wait for 3 weeks before marking any issue as stale and closing it.

If you think that this is a mistake, please drop a mail at tamalcodes@gmail.com, and we will get back to you.

Regards, 
Team Milan.
