### ISSUE TITLE
Add login with google 

### ISSUE THREAD

**Issue by Rishita1304** [tamalCodes/Milan#896]
### Description

adding login with google for easier login process. Please assign me this issue.

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
Please do not raise duplicate issues  - it is already been worked on.
