### ISSUE TITLE
[FEATURE] Footer Copyright `Milan` text Clickable

### ISSUE THREAD

**Issue by SyedImtiyaz-1** [tamalCodes/Milan#903]
### Description

Hello @NikhilRaikwar ,
I have a good idea that the footer copyright text can be upgraded like if some tap on the Milan Text or just hover on it it will show to underline hover also after clicking it will open the Home Page of the Milan Itself. 👍🏻 

### Screenshots

![image](https://github.com/tamalCodes/Milan/assets/121503426/27a7753f-9d9e-4cf2-bcaa-a017ddaee3e9)

### 🥦 Browser

Mozilla Firefox

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
Hi 90% of the times, the footers copyrights are non-clickable so this issue do not make any sense. Plus never make a PR without having the issue assigned to you.

I will be closing this for now.
