### ISSUE TITLE
[BUG] Overflow issue on 404 Page

### ISSUE THREAD

**Issue by SyedImtiyaz-1** [tamalCodes/Milan#905]
### Description

Hello @tamalCodes  ,
The 404 Error Page is not aligned properly.
Overlapping issue regarding to `404 Error Page`

### Video -

[Screencast from 28-06-23 08:21:01 PM IST.webm](https://github.com/tamalCodes/Milan/assets/121503426/18b060e3-2ee7-446e-a90c-080a106a6358)

### Browser 🥦

Mozilla Firefox

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by NikhilRaikwar** [comment]
Hey @SyedImtiyaz-1 I'm not an assigner @tamalCodes Sir is the assigner and mentor of the project.

**Comment by tamalCodes** [comment]
Hi @SyedImtiyaz-1 , please do not raise PRs until and unless you are assigned to it. It goes against our code of conduct.
Anyways for the first time, I will go review the PR.

**Comment by SyedImtiyaz-1** [comment]
@tamalCodes Thank you.
