### ISSUE TITLE
[FEATURE] want to add newsletter

### ISSUE THREAD

**Issue by iamparas0** [tamalCodes/Milan#907]
### Description

i want add a signup for newsletter section before footer and redisgn the product card designs
 please assign it to me 

### Screenshots

![Screenshot (14)](https://github.com/tamalCodes/Milan/assets/45733116/506e5315-be82-445b-ab05-fb767a095134)

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
Hi @iamparas0 , currently we are not looking to implement such a feature. Unfortunately, I will have to close this issue.
Thanks for raising it !
