### ISSUE TITLE
[BUG] Navbar remains open after clicking links on mobile

### ISSUE THREAD

**Issue by anamika7153** [tamalCodes/Milan#912]
### Description

- On mobile screens, when the user clicks on any link, navbar remains open.
- User has to manually close it.

### Expected Behavious

On mobile screens, when the user clicks any link, the navbar should close and the required page should be visible.

### Screenshots

https://github.com/tamalCodes/Milan/assets/66116440/07b43055-43e4-4da9-9b56-b1504bb4ed40

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
This is a bad UX to start with, do start working on it. Assigning it to you.
### Remember, Good PR makes a Good Developer !

We at Milan work hard to maintain the structure, and use conventional Pull request titles and commits.
**Please make sure that you have read our documentation on [Commiting guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#commits-) and [Pull request guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#pull-requests-).**

Without a proper template for the PR, not following the guidelines and spam might get the pull request closed, or banned.
