### ISSUE TITLE
adding link to the logo in the navbar and footer 

### ISSUE THREAD

**Issue by anuza08** [tamalCodes/Milan#917]
### Description

adding link to the logo in the navbar and footer logo that will direct to the main page.

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
We already have implemented in the Navbar, for the footer changes are ongoing.
