### ISSUE TITLE
adding dark mode to the website.

### ISSUE THREAD

**Issue by anuza08** [tamalCodes/Milan#918]
### Description

adding darkmode to the website

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
We are not looking for such changes as of now.
