### ISSUE TITLE
[DOCS] Implement Author Verification for GSSoC'23 Contributors in Issue Forms

### ISSUE THREAD

**Issue by Anmol-Baranwal** [tamalCodes/Milan#960]
### Description

> Suggestion
![image](https://github.com/tamalCodes/Milan/assets/74038190/1b65f257-8f3b-4946-8372-ee2b869f234a)

A better statement would be:
- I'm a GSSoC'23 Contributor

### Screenshots

> Similar to this
![image](https://github.com/tamalCodes/Milan/assets/74038190/bf1eec8c-4044-4205-8a03-bbfb9f7a5411)

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
Awesome !
