### ISSUE TITLE
Explore our shop navigating to code repo

### ISSUE THREAD

**Issue by SoundaryaKoutharapu** [tamalCodes/Milan#965]
### Description

On the home page,
when we click on explore our shop, it is navigating us to github code repo.

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
Hi @SoundaryaKoutharapu , well at that time we were in a beta phase of the shops - now that we released it, we will redirect it in our next release. The code is already in my local system - kudos for noticing it though !
