### ISSUE TITLE
[FEATURE] update styling of contact form

### ISSUE THREAD

**Issue by Anmol-Baranwal** [tamalCodes/Milan#967]
### Description

Here are the changes that I think would be better:

1. Improve the CTA to let others know that it is functional.

2. Increase the placeholder size of the `message` input.

3. Reduce the size of the title for specified viewport widths.

![image](https://github.com/tamalCodes/Milan/assets/74038190/8e5f9456-6e16-4212-b364-517fc1984d96)

4. Remove this effect (although I am not sure how to do so).

![image](https://github.com/tamalCodes/Milan/assets/74038190/60e46836-f0f0-4359-8cb7-3eaa1c55885e)

5. Remove autofill, which again I am not sure if it is needed.

> Let me know if you need these changes, and feel free to suggest other changes as well.
> Doing under GSSoC'23.

### Screenshots

![image](https://github.com/tamalCodes/Milan/assets/74038190/e9de3b14-286f-47eb-908b-208a4f829608)

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by Anmol-Baranwal** [comment]
@tamalCodes 
Please check this and let me know if this is needed.

**Comment by tamalCodes** [comment]
Hi @Anmol-Baranwal , the contact form will be totally removed in https://beta.milanhub.org, and we will be changing our report form to act like a contact form too. So if you want to work on re-vamping the report form please make an issue. 

I am closing this one for now.
