### ISSUE TITLE
[FEATURE] Scroll To Top button

### ISSUE THREAD

**Issue by pavitrachavda97** [tamalCodes/Milan#969]
### Description

Scroll to top button allows users to quickly navigate to the top of a page with a single click or tap. It offers a convenient way to return to the beginning of a long webpage without manually scrolling.

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
Please do not create duplicate issues, this is already being done in #944
