### ISSUE TITLE
[DOCS] README.md file enhancement

### ISSUE THREAD

**Issue by DivyanshiNarang** [tamalCodes/Milan#973]
### Description

Official documentation links are not added to these buttons. We can add official documentation links of the respective technologies used so that it will be helpful for new contributors.

### Screenshots

<img width="647" alt="image" src="https://github.com/tamalCodes/Milan/assets/74779601/99b5c47f-bec7-4115-9361-8ead644072b4">

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
Hey @DivyanshiNarang , that sounds good. Go ahead and start working on it.
### Remember, Good PR makes you a Good contributor !

We at Milan work hard to maintain the structure, and use conventional Pull request titles and commits. Without a proper template for the PR, not following the guidelines and spam might get the pull request closed, or banned.


- Please make sure that you have read our documentation on [Commiting guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#commits-) and [Pull request guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#pull-requests-).

- Once you have done the changes you can `request` a review. If I suggest changes again, do those and `request` a review again.

- Make sure you DO NOT modify the PR template that we have, use it as it is.

- Last but not least, be patient. It takes a while to review the changes and get it merged.
