### ISSUE TITLE
[DOCS] - Adding a socials section and badges to that section in the readme 

### ISSUE THREAD

**Issue by 1Shubham7** [tamalCodes/Milan#977]
### Description

![image](https://github.com/NageshMandal/Engineering-Notes-Website/assets/116020663/be1693e2-2172-4b6a-9237-810d7082600e)

This would help you improve your project react and your social media profile as well.
Please assign me this issue under GSSoC'23

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by 1Shubham7** [comment]
Please assign me this issue under GSSoC'23

**Comment by tamalCodes** [comment]
Hi @1Shubham7 , we will not be doing that right now, as we are we do not have a lot of social links and neither we have a community. So adding a dedicated section for the same is not needed as of now. 

Thank you so much for your time in raising the issue.
