### ISSUE TITLE
[FEATURE] Create a contributora page linked to the milan link in the footer

### ISSUE THREAD

**Issue by karthiknadar1204** [tamalCodes/Milan#981]
### Description

Currently in the footer, when we click on the Milan link at the extreme bottom, we get redirected to the website in another window again, I was thinking we could develop a contributors page using the github API showing all the contributors to the project in the form of cards . 

The cards would hold info like the avatar of the contributors, the number of commits to the project and a view button that shall redirect us to the contributors github profile.

This data would be dynamically fetched using the github API.

Please feel free to share any more suggestions .

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/tamalCodes/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)
- [X] I am a GSSoC23 contributor (blank for no).

**Comment by karthiknadar1204** [comment]
I would like to work on his issue under gssoc'23

**Comment by karthiknadar1204** [comment]
<img width="394" alt="Screenshot 2023-07-30 at 6 10 47 PM" src="https://github.com/tamalCodes/Milan/assets/95973644/4ebe00d9-c20f-4542-8407-0a09b6c6111d">


I am talking about the following link

**Comment by tamalCodes** [comment]
Hi there, thanks for raising this issue but unfortunately i will have to close this issue, because even if this is an amazing issue, we have like 135 contributors, so it makes no sense showing sooo many cards.

Plus anyonce can acess the contributors [here](https://github.com/tamalCodes/Milan/graphs/contributors)
