### ISSUE TITLE
[FEATURE]: Noticed we need style.yml File For Raising Enhancement related Requests

### ISSUE THREAD

**Issue by NarendraKoya999** [tamalCodes/Milan#990]
### Purpose of this Issue:
**style.yml (Custom ISSUE_TEMPLATE):**
- The style.yml file, on the other hand, serves as a custom ISSUE_TEMPLATE for issues related to coding style, code formatting, and linting rules within your GitHub repository. This template helps contributors or users report code style-related concerns or seek guidance on adhering to the project's coding standards.
- The contents of style.yml might include specific questions or prompts related to coding style, requesting users to provide examples of code snippets that need formatting adjustments or explanation. Additionally, you might include instructions on how to check code against the project's style guidelines and best practices.

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/tamalCodes/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)
- [X] I am a GSSoC23 contributor (blank for no).

**Comment by NarendraKoya999** [comment]
Hi @tamalCodes . Please review on this ISSUE as soon as Possible. Thank You !

**Comment by tamalCodes** [comment]
@NarendraKoya999 , please learn to be paitent. The issue will be reviewed as soon my hands are free.
Also go through the discussion: #995

**Comment by NarendraKoya999** [comment]
> @NarendraKoya999 , please learn to be paitent. The issue will be reviewed as soon my hands are free. Also go through the discussion: #995

Ok @tamalCodes 👍

**Comment by tamalCodes** [comment]
Hi there, though this sounds good but all the issues that we might ever have can be generalized into being either a 

- `bug` or `fix`
- `addition` or `feat`
- `dx` or `docs`

So with these generalizations at hand, it is not much needed to create more and more templates "specifically" for some particular work. It might lead to unessecary complexities for beginners and maintainers.
