### ISSUE TITLE
[Animation]  Animating header text

### ISSUE THREAD

**Issue by Dimple-Choudhary** [tamalCodes/Milan#996]
### Description

Adding 
Typing effect to H1 text on Milan website 
@tamalCodes  will you please assign me this issue under GSSOC'23?

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/tamalCodes/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)
- [X] I am a GSSoC23 contributor (blank for no).

**Comment by tamalCodes** [comment]
Hi @Dimple-Choudhary , if you have seen our new look at: https://beta.milanhub.org, you will notice that we are focused to keep our website minimal and focused. So for that reason we will not be continuing with this type of issues where we add any kind of animations.

Thankyou so much for your effor in raising up the issue.
